name: 'BitBucket Migration Compatibility Action'
description: 'Ensures (filesystem) compatibility with BitBucket pipelines.'
runs:
  using: "composite"
  steps:
    - shell: sh
      run: |
        # On alpine, install Docker CLI
        if ! command -v apt-get &> /dev/null
        then
           apk add --no-cache docker-cli
        fi

        chown -R $(id -u):$(id -g) "$(pwd)"
        chmod -R 777 "$(pwd)"
