name: 'BitBucket Migration Compatibility Action'
description: 'Ensures (filesystem) compatibility with BitBucket pipelines.'
runs:
  using: "composite"
  steps:
    - shell: sh
      run: |
        if command -v apt-get &> /dev/null
        then
           apt-get update
           apt-get install -y docker-ce-cli
        else
           apk add --no-cache docker-cli
        fi

        chown -R $(id -u):$(id -g) "$(pwd)"
        chmod -R 777 "$(pwd)"
