name: 'BitBucket Migration Compatibility Action'
description: 'Ensures (filesystem) compatibility with BitBucket pipelines.'
runs:
  using: "composite"
  steps:
    - shell: sh
      run: |
        chown -R $(id -u):$(id -g) "$(pwd)"
        chmod -R 777 "$(pwd)"
